import appJson from './app.json';
import { ExpoConfig } from 'expo/config';
import { withAndroidManifest, withDangerousMod } from '@expo/config-plugins';
import * as fs from 'fs';
import * as path from 'path';

function withRemovedMediaPermissions(config: ExpoConfig): ExpoConfig {
  return withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults;
    const permissions = manifest.manifest['uses-permission'] ?? [];
    const toRemove = new Set([
      'android.permission.READ_EXTERNAL_STORAGE',
      'android.permission.WRITE_EXTERNAL_STORAGE',
    ]);
    manifest.manifest['uses-permission'] = permissions.filter(
      (p: any) => !toRemove.has(p.$['android:name'])
    );
    return mod;
  });
}

/**
 * Copies assets/images/Splash-icon-Android12+.png into
 * android/app/src/main/res/drawable-v31/splashscreen_logo.png
 * after expo-splash-screen has run.
 *
 * Android resource resolution automatically selects drawable-v31/ on API 31+
 * (Android 12+) over drawable-{density}/, so windowSplashScreenAnimatedIcon
 * resolves to this asset on Android 12+ without any styles.xml change.
 *
 * Android 11 and below ignore drawable-v31/ entirely and continue using
 * the density PNGs generated by expo-splash-screen from splash-icon.png.
 *
 * The source file assets/images/Splash-icon-Android12+.png is NEVER modified —
 * it is only read (copyFileSync reads src, writes to dest in android/).
 */
function withAndroidV31Splash(config: ExpoConfig): ExpoConfig {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const platformRoot = cfg.modRequest.platformProjectRoot;

      const src = path.join(projectRoot, 'assets', 'images', 'Splash-icon-Android12+.png');
      const destDir = path.join(platformRoot, 'app', 'src', 'main', 'res', 'drawable-v31');
      const dest = path.join(destDir, 'splashscreen_logo.png');

      if (!fs.existsSync(src)) {
        console.warn('[withAndroidV31Splash] Source not found, skipping:', src);
        return cfg;
      }

      fs.mkdirSync(destDir, { recursive: true });
      fs.copyFileSync(src, dest);
      console.log('[withAndroidV31Splash] Copied Splash-icon-Android12+.png → drawable-v31/splashscreen_logo.png');

      return cfg;
    },
  ]);
}

const isExpoGo = false;

const config: ExpoConfig = {
  ...(appJson.expo as unknown as ExpoConfig),
  extra: {
    ...(appJson.expo.extra as Record<string, unknown>),
    eas: {
      projectId: '2e1c9549-69cf-4cd3-b5ca-4b922181897b',
    },
  },
  plugins: isExpoGo
    ? (appJson.expo.plugins as any[]).filter((p) => {
        const name = Array.isArray(p) ? p[0] : p;
        return name !== 'onesignal-expo-plugin';
      })
    : (appJson.expo.plugins as any[]),
};

export default withAndroidV31Splash(withRemovedMediaPermissions(config));
